export const WORK_TYPE_LOAD_REQUEST = "WORK_TYPE_LOAD_REQUEST";
export const WORK_TYPE_LOAD_SUCCESS = "WORK_TYPE_LOAD_SUCCESS";
export const WORK_TYPE_LOAD_FAIL = "WORK_TYPE_LOAD_FAIL";
export const WORK_TYPE_LOAD_RESET = "WORK_TYPE_LOAD_RESET";