export const WORK_LOAD_REQUEST = "WORK_LOAD_REQUEST";
export const WORK_LOAD_SUCCESS = "WORK_LOAD_SUCCESS";
export const WORK_LOAD_FAIL = "WORK_LOAD_FAIL";
export const WORK_LOAD_RESET = "WORK_LOAD_RESET";
