export const WORK_LOAD_REQUEST = "WORK_LOAD_REQUEST";
export const WORK_LOAD_SUCCESS = "WORK_LOAD_SUCCESS";
export const WORK_LOAD_FAIL = "WORK_LOAD_FAIL";
export const WORK_LOAD_RESET = "WORK_LOAD_RESET";


export const REGISTER_JOB_REQUEST = "REGISTER_JOB_REQUEST"
export const REGISTER_JOB_SUCCESS = "REGISTER_JOB_SUCCESS"
export const REGISTER_JOB_FAIL = "REGISTER_JOB_FAIL"
export const REGISTER_JOB_RESET = "REGISTER_JOB_RESET"