export const WORK_LOAD_REQUEST = "WORK_LOAD_REQUEST";
export const WORK_LOAD_SUCCESS = "WORK_LOAD_SUCCESS";
export const WORK_LOAD_FAIL = "WORK_LOAD_FAIL";
export const WORK_LOAD_RESET = "WORK_LOAD_RESET";


export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_FAIL = "ADD_TASK_FAIL"
export const ADD_TASK_RESET = "ADD_TASK_RESET"